import './globals.css'
import { Montserrat } from 'next/font/google';
import type { Metadata } from 'next'


const montserrat = Montserrat ({
  subsets:["latin"],
  variable: "--font-mont",
  weight: ["100","200", "300", "400", "500", "600", "700", "800", "900"]
})

export const metadata: Metadata = {
  title: 'personal portfolio',
  description: 'Generated by shubhanker saxena',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  )
}
